#!/usr/bin/env python3
"""
Real-time SYN-flood detection pipeline (single-view all-packets).

This pipeline:
1) Captures live traffic with tcpdump into rotating PCAP files.
2) For each completed window PCAP:
   - converts packets into 224x224 grayscale images (byte->image, paper methodology)
   - uses all packets (no syn_only branch)
   - runs ResNeXt inference on the image batch
   - logs prediction and optionally sends notification
3) Runs as a long-lived process (live mode) and logs detections.

Offline verification:
  python run_pipeline.py --pcap /path/to/sample.pcap
"""

from __future__ import annotations

import argparse
import glob
import math
import os
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional, Tuple
import json
import urllib.request

import numpy as np
from PIL import Image

# Project imports
_ROOT = Path(__file__).resolve().parent
if str(_ROOT) not in os.sys.path:
    os.sys.path.insert(0, str(_ROOT))

import mindspore as ms
from mindspore import ops
from mindcv.models import create_model

from scripts.pcap_to_images import iter_pcap_packets, packet_to_image_224x224


IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32).reshape(1, 1, 3)
IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32).reshape(1, 1, 3)


def center_crop_pil(img: Image.Image, crop_size: int) -> Image.Image:
    """Center-crop a PIL image."""
    w, h = img.size
    left = (w - crop_size) // 2
    top = (h - crop_size) // 2
    return img.crop((left, top, left + crop_size, top + crop_size))


def preprocess_gray224_to_chw(img_2d: np.ndarray, img_size: int = 224, resize_size: int = 256) -> np.ndarray:
    """
    Match eval preprocessing in this repo.

    Input:
      img_2d: (224,224) grayscale uint8 image generated by scripts/pcap_to_images.py
    Output:
      CHW float32 array, shape (3,224,224), normalized with ImageNet mean/std.
    """
    if img_2d.ndim != 2:
        raise ValueError(f"Expected grayscale 2D array, got shape={img_2d.shape}")

    # PIL grayscale -> RGB (replicate channels) to match train/eval pipeline
    pil_l = Image.fromarray(img_2d.astype(np.uint8), mode="L")
    pil_rgb = pil_l.convert("RGB")

    if resize_size and resize_size != img_size:
        pil_resized = pil_rgb.resize((resize_size, resize_size), Image.BILINEAR)
        pil_crop = center_crop_pil(pil_resized, img_size)
    else:
        pil_crop = pil_rgb.resize((img_size, img_size), Image.BILINEAR)

    arr = np.asarray(pil_crop, dtype=np.float32) / 255.0  # HWC float32 in [0,1]
    arr = (arr - IMAGENET_MEAN) / IMAGENET_STD
    arr = np.transpose(arr, (2, 0, 1))  # CHW
    return arr.astype(np.float32)


def convert_pcap_to_images_all_packets(
    pcap_path: Path,
    max_images: int,
) -> List[np.ndarray]:
    """
    Convert a PCAP window into a single image list using all packets.
    """
    images: List[np.ndarray] = []

    for pkt_bytes in iter_pcap_packets(str(pcap_path)):
        if len(images) >= max_images:
            break
        img = packet_to_image_224x224(pkt_bytes, syn_only=False)
        if img is not None:
            images.append(img)

    return images


def load_model(ckpt_path: Path, device_target: str = "CPU") -> ms.nn.Cell:
    """Load ResNeXt model + checkpoint for inference."""
    ms.set_context(mode=ms.GRAPH_MODE, device_target=device_target)
    net = create_model(model_name="resnext50_32x4d", pretrained=False, num_classes=2)
    params = ms.load_checkpoint(str(ckpt_path))
    ms.load_param_into_net(net, params)
    net.set_train(False)
    return net


@dataclass
class InferenceResult:
    pred_label: str
    pred_idx: int
    p_ddos: float
    probs_view: Optional[np.ndarray]  # shape (2,)
    images_count: int


def infer_on_images(net: ms.nn.Cell, images: List[np.ndarray], batch_size: int = 32) -> Optional[np.ndarray]:
    """
    Run inference over a list of grayscale images and return mean probabilities (2,)
    for that view.
    """
    if not images:
        return None

    softmax = ops.Softmax(axis=1)

    probs_accum: List[np.ndarray] = []
    for i in range(0, len(images), batch_size):
        chunk = images[i : i + batch_size]
        batch = np.stack([preprocess_gray224_to_chw(img) for img in chunk], axis=0)  # NCHW
        x = ms.Tensor(batch, dtype=ms.float32)
        logits = net(x)
        probs = softmax(logits).asnumpy()  # (N,2)
        probs_accum.append(probs)

    probs_all = np.concatenate(probs_accum, axis=0)  # (N,2)
    mean_probs = probs_all.mean(axis=0)  # (2,)
    return mean_probs.astype(np.float32)


def notify_if_needed(notify_url: str, payload: dict) -> None:
    """Optional HTTP POST notification (best-effort)."""
    if not notify_url:
        return
    try:
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(notify_url, data=data, headers={"Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=5) as resp:
            _ = resp.read()
    except Exception:
        # Notification is best-effort; never crash the pipeline.
        return


def infer_pcap_window(
    net: ms.nn.Cell,
    pcap_path: Path,
    max_images_per_window: int,
    batch_size: int,
) -> InferenceResult:
    """Run inference on one PCAP file; no logging or notifications."""
    images = convert_pcap_to_images_all_packets(pcap_path, max_images=max_images_per_window)
    probs = infer_on_images(net, images, batch_size=batch_size)
    if probs is None:
        probs = np.array([0.0, 1.0], dtype=np.float32)
    pred_idx = int(np.argmax(probs))
    pred_label = "ddos" if pred_idx == 0 else "normal"
    p_ddos = float(probs[0])
    return InferenceResult(
        pred_label=pred_label,
        pred_idx=pred_idx,
        p_ddos=p_ddos,
        probs_view=probs,
        images_count=len(images),
    )


def append_detection_log(log_file: Path, payload: dict) -> None:
    log_file.parent.mkdir(parents=True, exist_ok=True)
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(json.dumps(payload) + "\n")


def process_pcap_window(
    net: ms.nn.Cell,
    pcap_path: Path,
    max_images_per_window: int,
    resize_size: int,
    img_size: int,
    batch_size: int,
    notify_url: str,
    log_file: Path,
    *,
    alert_min_p_ddos: float = 0.0,
    alert_consecutive: int = 1,
) -> InferenceResult:
    """Infer on one PCAP (``--pcap`` offline mode), append JSON log, optional webhook.

    For a single window, ``streak`` is 1 if the prediction qualifies (DDoS and
    ``p_ddos`` meets ``alert_min_p_ddos``), else 0. ``alert`` is true when the
    streak meets ``alert_consecutive`` (default 1 = same as legacy notify-on-ddos).
    """
    _ = resize_size, img_size  # reserved for future parameterized preprocess
    result = infer_pcap_window(net, pcap_path, max_images_per_window, batch_size)

    qualifies = result.pred_label == "ddos" and result.p_ddos >= alert_min_p_ddos
    streak = 1 if qualifies else 0
    fired = qualifies and streak >= alert_consecutive

    payload = {
        "ts": time.time(),
        "pcap": str(pcap_path),
        "pred": result.pred_label,
        "p_ddos": result.p_ddos,
        "images_all": result.images_count,
        "streak": streak,
        "alert": fired,
        "alert_min_p_ddos": alert_min_p_ddos,
        "alert_consecutive": alert_consecutive,
    }

    append_detection_log(log_file, payload)

    if fired:
        notify_if_needed(notify_url, payload)

    return result


def start_tcpdump(
    interface: str,
    capture_dir: Path,
    window_sec: float,
    tcpdump_err_log: Path,
) -> subprocess.Popen:
    """Start tcpdump with rotating PCAP output.

    tcpdump stderr is persisted so failures are visible (tcpdump may exit even if
    the parent Python process keeps running).
    """
    capture_dir.mkdir(parents=True, exist_ok=True)

    # strftime in -w is expanded only when -G uses whole seconds on tcpdump 4.99+;
    # fractional -G (e.g. 0.3) leaves literal "%Y%m%d..." in the filename, breaks rotation,
    # and deleting that path while tcpdump still writes causes capture to go to a deleted inode
    # so glob finds no new PCAPs and detections.log stops updating.
    g_tcpdump = max(1, int(math.ceil(float(window_sec))))
    pcap_pattern = str(capture_dir / "win_%Y%m%d_%H%M%S.pcap")

    cmd = [
        "tcpdump",
        "-i",
        interface,
        "-nn",
        "-s",
        "0",
        "-G",
        str(g_tcpdump),
        "-w",
        pcap_pattern,
    ]
    tcpdump_err_log.parent.mkdir(parents=True, exist_ok=True)
    err_fh = open(tcpdump_err_log, "a", encoding="utf-8")
    # Keep stdout quiet; errors go to a file so systemd/journal stays clean.
    return subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=err_fh)


def live_loop(
    net: ms.nn.Cell,
    interface: str,
    capture_dir: Path,
    window_sec: float,
    max_images_per_window: int,
    max_pending_pcaps: int,
    poll_interval_sec: float,
    batch_size: int,
    notify_url: str,
    log_file: Path,
    alert_min_p_ddos: float,
    alert_consecutive: int,
) -> None:
    tcpdump_err_log = log_file.parent / "tcpdump.err.log"
    tcpdump_proc: Optional[subprocess.Popen] = None
    tcpdump_restart_count = 0
    processed: set[str] = set()
    ddos_streak = 0

    try:
        while True:
            # If tcpdump exits for any reason, we must restart it; otherwise the
            # main loop will just keep polling an empty capture dir forever.
            if tcpdump_proc is None or (tcpdump_proc.poll() is not None):
                rc = None if tcpdump_proc is None else tcpdump_proc.poll()
                tcpdump_restart_count += 1
                sleep_s = min(30.0, 1.0 + (tcpdump_restart_count * 2.0))
                print(f"[ERROR] tcpdump stopped (rc={rc}); restarting in {sleep_s:.1f}s")
                time.sleep(sleep_s)
                tcpdump_proc = start_tcpdump(
                    interface=interface,
                    capture_dir=capture_dir,
                    window_sec=window_sec,
                    tcpdump_err_log=tcpdump_err_log,
                )

            pcaps = sorted(glob.glob(str(capture_dir / "*.pcap")))
            if not pcaps:
                time.sleep(poll_interval_sec)
                continue

            # Drop policy: if backlog is too large, remove oldest unprocessed pcaps.
            unprocessed = [p for p in pcaps if p not in processed]
            if len(unprocessed) > max_pending_pcaps:
                to_drop = unprocessed[: len(unprocessed) - max_pending_pcaps]
                for p in to_drop:
                    processed.add(p)
                    try:
                        os.remove(p)
                    except FileNotFoundError:
                        pass
                # Do not process paths we just deleted (was causing FileNotFoundError on getmtime).
                unprocessed = unprocessed[len(to_drop) :]

            # Only process PCAPs that are likely "closed"
            now = time.time()
            for pcap_path in unprocessed:
                try:
                    mtime = os.path.getmtime(pcap_path)
                except FileNotFoundError:
                    # tcpdump may rotate/remove between glob and here; skip until next poll.
                    continue
                age = now - mtime
                if age < (window_sec + 1.0):
                    continue

                processed.add(pcap_path)
                result = infer_pcap_window(
                    net=net,
                    pcap_path=Path(pcap_path),
                    max_images_per_window=max_images_per_window,
                    batch_size=batch_size,
                )
                qualifies = result.pred_label == "ddos" and result.p_ddos >= alert_min_p_ddos
                if qualifies:
                    ddos_streak += 1
                else:
                    ddos_streak = 0
                alert_fired = qualifies and ddos_streak >= alert_consecutive
                payload = {
                    "ts": time.time(),
                    "pcap": pcap_path,
                    "pred": result.pred_label,
                    "p_ddos": result.p_ddos,
                    "images_all": result.images_count,
                    "streak": ddos_streak,
                    "alert": alert_fired,
                    "alert_min_p_ddos": alert_min_p_ddos,
                    "alert_consecutive": alert_consecutive,
                }
                append_detection_log(log_file, payload)
                if alert_fired:
                    notify_if_needed(notify_url, payload)

                # Remove processed PCAP to bound disk usage.
                try:
                    os.remove(pcap_path)
                except FileNotFoundError:
                    pass

            time.sleep(poll_interval_sec)
    finally:
        try:
            if tcpdump_proc is not None:
                tcpdump_proc.terminate()
        except Exception:
            pass


def main() -> int:
    parser = argparse.ArgumentParser(description="ResNeXt SYN-flood detection pipeline (single-view all-packets).")
    parser.add_argument(
        "--ckpt",
        type=str,
        default="model/per_second_0p3_focal_v2/resnext50_32x4d_best.ckpt",
        help="Path to MindSpore checkpoint (.ckpt); primary model is 0.3s focal v2.",
    )
    parser.add_argument("--interface", type=str, default="eth0", help="Network interface for tcpdump.")
    parser.add_argument("--capture-dir", type=str, default="/var/capture", help="Directory for tcpdump rotating PCAPs.")
    parser.add_argument("--log-file", type=str, default="/var/log/synflood-detector/detections.log")
    parser.add_argument("--notify-url", type=str, default="", help="Optional webhook URL (POST JSON).")

    parser.add_argument(
        "--window-sec",
        type=float,
        default=0.3,
        help="PCAP rotation window in seconds (match 0.3s training).",
    )
    parser.add_argument("--max-images-per-window", type=int, default=50, help="Max packet-images per window.")
    parser.add_argument("--max-pending-pcaps", type=int, default=3, help="Max unprocessed PCAPs before dropping oldest.")
    parser.add_argument("--poll-interval-sec", type=float, default=1.0, help="Polling interval for PCAP processing.")

    parser.add_argument("--batch-size", type=int, default=16, help="Inference batch size.")

    parser.add_argument("--pcap", type=str, default="", help="Offline: process a single PCAP and exit.")
    parser.add_argument("--live", action="store_true", help="Run live capture loop.")
    parser.add_argument(
        "--alert-min-p-ddos",
        type=float,
        default=0.0,
        help="Count toward DDoS streak only if p_ddos >= this (0 = any argmax DDoS).",
    )
    parser.add_argument(
        "--alert-consecutive",
        type=int,
        default=1,
        help="Require this many consecutive qualifying DDoS windows before alert/webhook.",
    )

    args = parser.parse_args()

    ckpt_path = Path(args.ckpt)
    if not ckpt_path.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {ckpt_path}")

    # CPU inference
    net = load_model(ckpt_path=ckpt_path, device_target="CPU")

    capture_dir = Path(args.capture_dir)
    log_file = Path(args.log_file)

    if args.pcap:
        process_pcap_window(
            net=net,
            pcap_path=Path(args.pcap),
            max_images_per_window=args.max_images_per_window,
            resize_size=256,
            img_size=224,
            batch_size=args.batch_size,
            notify_url=args.notify_url,
            log_file=log_file,
            alert_min_p_ddos=args.alert_min_p_ddos,
            alert_consecutive=args.alert_consecutive,
        )
        return 0

    if args.live:
        live_loop(
            net=net,
            interface=args.interface,
            capture_dir=capture_dir,
            window_sec=args.window_sec,
            max_images_per_window=args.max_images_per_window,
            max_pending_pcaps=args.max_pending_pcaps,
            poll_interval_sec=args.poll_interval_sec,
            batch_size=args.batch_size,
            notify_url=args.notify_url,
            log_file=log_file,
            alert_min_p_ddos=args.alert_min_p_ddos,
            alert_consecutive=max(1, args.alert_consecutive),
        )
        return 0

    raise ValueError("Specify either --pcap for offline test or --live for live capture.")


if __name__ == "__main__":
    raise SystemExit(main())

